# wagglebot shell environment.
#
# The managed block in ~/.zshenv (and ~/.bashrc, when that file exists) sources this file.
# It exports every line of the gitignored .env.credentials file of the company repository,
# so an agent harness started from this shell can expand ${VAR} in its MCP config.
#
# Do not edit this file. A wagglebot upgrade replaces it. Company changes belong in the
# company repository.
if [ -n "${WAGGLEBOT_COMPANY_REPO:-}" ] && [ -r "$WAGGLEBOT_COMPANY_REPO/.env.credentials" ]; then
  set -a
  . "$WAGGLEBOT_COMPANY_REPO/.env.credentials"
  set +a
fi
