# wagglebot shell environment.
#
# The managed block in the startup file of your shell (~/.zshenv for zsh, ~/.bashrc for
# bash) sources this file.
# It exports the personal credential file selected by the managed shell block,
# so an agent harness started from this shell can expand ${VAR} in its MCP config.
#
# Do not edit this file. A wagglebot upgrade replaces it. Company changes belong in the
# company repository.
if [ -n "${WAGGLEBOT_CREDENTIALS_FILE:-}" ] && [ -r "$WAGGLEBOT_CREDENTIALS_FILE" ]; then
  set -a
  . "$WAGGLEBOT_CREDENTIALS_FILE"
  set +a
elif [ -z "${WAGGLEBOT_CREDENTIALS_FILE:-}" ] && [ -n "${WAGGLEBOT_COMPANY_REPO:-}" ] && [ -r "$WAGGLEBOT_COMPANY_REPO/.env.credentials" ]; then
  # Preserve older managed blocks until the next shell synchronization.
  set -a
  . "$WAGGLEBOT_COMPANY_REPO/.env.credentials"
  set +a
fi
