import { existsSync, readdirSync, readFileSync, rmSync, statSync } from "node:fs";
import { join } from "node:path";
import { writeFileAtomic } from "../atomic-write";
import type { Harness, ProjectTarget } from "../harness";
import { HARNESSES } from "../harness";
import { BLOCK_BEGIN, BLOCK_END, removeManagedBlock, renderManagedBlock } from "../managed-block";
import { findProjectRoot } from "../project-root";
import type { Reporter } from "../report";

export const INSTRUCTIONS_DIR = ".agents/instructions";
const NOTE = `<!-- Generated by wagglebot sync-project from ${INSTRUCTIONS_DIR}/*.md. Edit the source files, not this block. -->`;

// One file to write, with every harness that reads it. Codex, Junie, and Cline share AGENTS.md, so
// the harness table yields three entries for one path and the command writes that path once.
export type ResolvedTarget = Omit<ProjectTarget, "path"> & { relative: string; harnesses: string[] };

export function projectTargets(harnesses: Harness[]): ResolvedTarget[] {
  const byPath = new Map<string, ResolvedTarget>();
  for (const harness of harnesses) {
    const target = harness.projectTarget;
    if (target === undefined) continue;
    const seen = byPath.get(target.path);
    if (seen === undefined) {
      const { path: relativePath, ...rest } = target;
      byPath.set(relativePath, { ...rest, relative: relativePath, harnesses: [harness.name] });
      continue;
    }
    if (seen.mode !== target.mode || seen.importLine !== target.importLine) {
      throw new Error(`harness table: ${harness.name} and ${seen.harnesses[0]} disagree about ${target.path}`);
    }
    seen.harnesses.push(harness.name);
    seen.warnBytes = minDefined(seen.warnBytes, target.warnBytes);
    seen.limitBytes = minDefined(seen.limitBytes, target.limitBytes);
  }
  return [...byPath.values()];
}

const minDefined = (a?: number, b?: number): number | undefined =>
  a === undefined ? b : b === undefined ? a : Math.min(a, b);

// Every non-empty .agents/instructions/*.md file, sorted by name. A whitespace-only file counts as absent.
export function readInstructionSources(root: string): string[] {
  const dir = join(root, INSTRUCTIONS_DIR);
  if (!existsSync(dir) || !statSync(dir).isDirectory()) return [];
  return readdirSync(dir)
    .filter((name) => name.endsWith(".md") && statSync(join(dir, name)).isFile())
    .sort()
    .map((name) => readFileSync(join(dir, name), "utf8").trim())
    .filter((text) => text !== "");
}

export const renderInstructions = (sources: string[]): string => [NOTE, ...sources].join("\n\n");
const renderImport = (importLine: string): string => `${NOTE}\n\n${importLine}`;
const bytes = (text: string): number => Buffer.byteLength(text, "utf8");
const readIfExists = (path: string): string | undefined => (existsSync(path) ? readFileSync(path, "utf8") : undefined);

type Change =
  | { relative: string; kind: "ok"; detail: string }
  | { relative: string; kind: "create" | "update"; next: string; detail: string }
  | { relative: string; kind: "remove-block"; next: string }
  | { relative: string; kind: "remove-file" };

// Every target sits inside the repository, so git is the backup and the undo. The command keeps no
// state of its own: a file that holds nothing but the managed block is a file wagglebot generated.
export function runSyncProject(deps: { cwd: string; reporter: Reporter; harnesses?: Harness[] }): number {
  const { reporter } = deps;
  reporter.section("Project instruction sync");
  const root = findProjectRoot(deps.cwd);
  const sources = readInstructionSources(root);
  const targets = projectTargets(deps.harnesses ?? HARNESSES);

  // Preflight: compute every output before the first mutation. A malformed marker or a hard size
  // limit therefore aborts the whole run with every file unchanged.
  const plan: Change[] = [];
  const warnings: string[] = [];
  if (sources.length > 0) {
    const body = renderInstructions(sources);
    for (const target of targets) {
      const existing = readIfExists(join(root, target.relative));
      const content = target.mode === "import" ? renderImport(target.importLine ?? "") : body;
      const { next, changed } = renderManagedBlock(existing ?? "", content);
      const fileBytes = bytes(next);
      const sizes = `block ${bytes(`${BLOCK_BEGIN}\n${content}\n${BLOCK_END}`)} B, file ${fileBytes} B`;
      const readers = target.harnesses.join(", ");
      if (target.limitBytes !== undefined && fileBytes > target.limitBytes) {
        throw new Error(
          `${target.relative} would be ${fileBytes} bytes, above the documented hard limit of ${target.limitBytes} bytes for ${readers}. No file changed.`,
        );
      }
      if (target.warnBytes !== undefined && fileBytes > target.warnBytes) {
        warnings.push(
          `${target.relative}: ${sizes}. The default Codex project instruction budget is ${target.warnBytes} bytes, ` +
            "and Codex loads global and nested AGENTS.md files under that same budget. This command measures only " +
            "the root file, so it cannot tell whether the effective chain fits, and a smaller root file may not fit either.",
        );
      }
      const detail = `(${readers}), ${sizes}`;
      if (existing === undefined)
        plan.push({ relative: target.relative, kind: "create", next, detail: `created ${detail}` });
      else if (changed) plan.push({ relative: target.relative, kind: "update", next, detail: `synced ${detail}` });
      else plan.push({ relative: target.relative, kind: "ok", detail: `already ok ${detail}` });
    }
  } else {
    // No source: remove what wagglebot wrote. A file that is only the block goes away. Any other
    // file loses the block and keeps everything else.
    for (const target of targets) {
      const existing = readIfExists(join(root, target.relative));
      if (existing === undefined) continue;
      const { next, changed } = removeManagedBlock(existing);
      if (!changed) continue;
      if (next.trim() === "") plan.push({ relative: target.relative, kind: "remove-file" });
      else plan.push({ relative: target.relative, kind: "remove-block", next });
    }
    if (plan.length === 0) {
      reporter.item(INSTRUCTIONS_DIR, "skipped", "no source file and no managed block, so nothing changes");
      return 0;
    }
  }

  for (const change of plan) {
    const absolute = join(root, change.relative);
    try {
      if (change.kind === "ok") reporter.item(change.relative, "ok", change.detail);
      else if (change.kind === "remove-file") {
        rmSync(absolute);
        reporter.item(change.relative, "updated", "removed the generated file");
      } else if (change.kind === "remove-block") {
        writeFileAtomic(absolute, change.next);
        reporter.item(change.relative, "updated", "removed the managed block");
      } else {
        writeFileAtomic(absolute, change.next);
        reporter.item(change.relative, change.kind === "create" ? "installed" : "updated", change.detail);
      }
    } catch (error) {
      reporter.item(change.relative, "failed", error instanceof Error ? error.message : String(error));
    }
  }
  for (const warning of warnings) reporter.warn(warning);
  return reporter.failed() ? 1 : 0;
}
